# Generated by Django 3.1.4 on 2021-08-30 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_auto_20210829_0631'),
    ]

    operations = [
        migrations.CreateModel(
            name='settlement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupName', models.CharField(max_length=128)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('done_at', models.DateTimeField(auto_now_add=True)),
                ('groupAdmin', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='SettleAdmin', to=settings.AUTH_USER_MODEL)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1settlement', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2settlement', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Settelment',
        ),
    ]
